"""remove is_online from users

Revision ID: 582afbaa9269
Revises: 346cfa83291d
Create Date: 2025-12-25 07:56:47.295705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582afbaa9269'
down_revision: Union[str, Sequence[str], None] = '346cfa83291d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_online')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
